### ISSUE TITLE
Can you please tell which file icon theme you are using in those screenshots? 

### ISSUE THREAD

**Issue by cixwaregagan** [juanmnl/vs-hydra#1]
I'm currently using vscode icons but it doesn't look as slick as your screenshots 😒. I've searched everywhere in the vscode market place but couldn't find it. 
So, Can you please tell which file icon theme you are using?

P.S: Great theme. I'm really liking it.

**Comment by zxuqian** [comment]
I'd like to know either.

**Comment by juanmnl** [comment]
Hey @cixwaregagan, so sorry for the extremely late reply, work's been crazy and forgot to check my personal github.

I'm not sure what the icons were at that time, but I'm guessing it's the `file-icons-colourless` option from `settings > appearance > icon theme` (or at least they are very similar and what I use today)

I think it used to be a package and now it comes baked in.

cc/ @zxuqian 

<img width="838" alt="Screen Shot 2020-08-08 at 10 14 58" src="https://user-images.githubusercontent.com/699945/89713919-95b55c00-d960-11ea-8ef8-c00ed7e8a6ca.png">

**Comment by zxuqian** [comment]
Thank you for the reply! It is still useful for me! The `file-icons-colourless` option actually belongs to the `file-icons` plugin. Thanks for sharing your amazing theme!

**Comment by juanmnl** [comment]
Ohh, that's great (long time not changing any config from vscode, so wasn't sure as I didn't find it on the extensions folder)
Good catch! 😅
tx
